# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-key-state-error',
                'doc_host': 'https://deven-gqc.github.io',
                'git_url': 'https://github.com/deven-gqc/test-key-state-error',
                'lib_path': 'test_key_state_error'},
  'syms': {'test_key_state_error.core': {'test_key_state_error.core.foo': ('core.html#foo', 'test_key_state_error/core.py')}}}